### ISSUE TITLE
Try RandomForestRegressor

### ISSUE THREAD

**Issue by Jiri-Kremser** [hawkular/hawkular-datamining#15]
it's quite new, but it's worth looking whether it has better results than the currently used `StreamingLinearRegressionWithSGD`
https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/regression/RandomForestRegressor.scala

edit: I am not sure if it can be used in the streaming manner

**Comment by pavolloffay** [comment]
Regression models won't be used.
